services:
  nginx:
    container_name: container-nginx
    # 이미지 지정 - 직접 작성한 dockerfile을 실행하여 컨테이너 생성
    build:
      context: ./nginx
      dockerfile: dockerfile
    volumes:
      - ./nginx/www:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    restart: always

  php:
    container_name: container-php
    image: php:fpm
    build:
      context: ./nginx/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/www:/var/www/html
    environment:
      - SESSION_HANDLER=redis
      - SESSION_PATH=tcp://redis:6379?auth=redis

  redis:
    container_name: container-redis
    image: redis:7.4.0
    build:
      context: ./docker-redis
      dockerfile: dockerfile
    depends_on:
      - nginx
    volumes:
      - ./docker-redis/redis_data:/data/
    ports:
      - "6379:6379"
    links:
      - php
    restart: always
